# Generated by Django 5.1.3 on 2024-12-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="shop",
            field=models.IntegerField(),
        ),
    ]
