version: ‘3.6’
services:
#  django:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8000:8000"
#    environment:
#      - DJANGO_SETTINGS_MODULE=endterm.settings
#    volumes:
#      - .:/app
  prometheus:
   image: prom/prometheus:latest
   volumes:
     - ./prometheus/:/etc/prometheus/
     - ./prometheus.yml:/etc/prometheus/prometheus.yml
   command:
     - '--config.file=/etc/prometheus/prometheus.yml'
     - '--web.enable-lifecycle'
   ports:
     - 9090:9090
  grafana:
   image: grafana/grafana:latest
   ports:
     - 3060:3000